[package]
name = "zed"
version = "0.1.0"
authors = ["M Farkas-Dyck <strake888@gmail.com>"]

[dependencies]
libc = "*"
rustbox = "*"

[dependencies.real]
path = "../libreal.rs"

[dependencies.syscall]
path = "../syscall.rs"
